resources:
- repo: self
queue:
  name: Hosted macOS
  demands: Xamarin.iOS

variables:
  BuildConfiguration: 'Release'
steps:
- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    configuration: '$(BuildConfiguration)'

    buildForSimulator: true


- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack

    packagesToPack: '**/Softeq.ImagePicker.csproj'


- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/*.nupkg'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


