resources:
- repo: self
queue:
  name: Hosted macOS
  demands: Xamarin.iOS

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'


- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    buildForSimulator: true


- task: NuGetCommand@2
  displayName: 'NuGet restore'

  enabled: false


